### ISSUE TITLE
Client drops the server if the server doesn't respond within set interval

### ISSUE THREAD

**Issue by markusranda** [markusranda/IE303812-TrosteSpel#26]

**Comment by 0us** [comment]
https://github.com/markusranda/IE303812-TrosteSpel/commit/f5d51367149eb03d1d68e7af342fd88b1935eb4f

 - Client drops the server if the server doesn't respond within set interval
 - Implement "TCPMessage" class, containing an event and a String[] object. Event can be for instance "Connect" or "Disconnect"
